global_env: route53 docker_registry gocd worker_dev worker_qa

destroy_global_env: destroy_worker_dev destroy_worker_qa destroy_gocd destroy_docker_registry destroy_route53

.PHONY: global_env destroy_global_env