#!/usr/bin/env bash

# Default Environment variables
COREOS_UPDATE_CHANNEL=${COREOS_UPDATE_CHANNEL}        # stable/beta/alpha
VM_TYPE=${VM_TYPE}                                        # hvm/pv - note: t1.micro supports only pv type

# domain for route53
PRIVATE_DOMAIN=${PRIVATE_DOMAIN}
PUBLIC_DOMAIN=${PUBLIC_DOMAIN}

# elb variables
CERTIFICATE_BODY_PATH=${CERTIFICATE_BODY_PATH}
CERTIFICATE_CHAIN_PATH=${CERTIFICATE_CHAIN_PATH}
PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}

# worker_dev variables
DEV_APP_FROM_PORT=${DEV_APP_FROM_PORT}
DEV_APP_TO_PORT=${DEV_APP_TO_PORT}
# worker_qa variables
QA_APP_FROM_PORT=${QA_APP_FROM_PORT}
QA_APP_TO_PORT=${QA_APP_TO_PORT}

# aurora DB variables
AURORA_DB_NAME=${AURORA_DB_NAME}
AURORA_DB_USERNAME=${AURORA_DB_USERNAME}
AURORA_DB_PASSWORD=${AURORA_DB_PASSWORD}
AURORA_DB_INSTANCE_COUNT=${AURORA_DB_INSTANCE_COUNT}
AURORA_DB_INSTANCE_CLASS=${AURORA_DB_INSTANCE_CLASS}
AURORA_DB_PUBLICLY_ACCESSIBLE=${AURORA_DB_PUBLICLY_ACCESSIBLE}

AWS_PROFILE=${AWS_PROFILE}
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
AWS_REGION=$($DIR/read_cfg.sh $HOME/.aws/config "profile $AWS_PROFILE" region)

# Get options from the command line
while getopts ":c:z:t:" OPTION
do
    case $OPTION in
        c)
          COREOS_UPDATE_CHANNEL=$OPTARG
          ;;
        z)
          AWS_REGION=$OPTARG
          ;;
        t)
          VM_TYPE=$OPTARG
          ;;
        *)
          echo "Usage: $(basename $0) -c <stable|beta|alpha> -z <aws zone> -t <hvm|pv>"
          exit 0
          ;;
    esac
done


# Get the AMI id
url=`printf "http://%s.release.core-os.net/amd64-usr/current/coreos_production_ami_%s_%s.txt" $COREOS_UPDATE_CHANNEL $VM_TYPE $AWS_REGION`
cat <<EOF
# Generated by scripts/get-vars.sh
variable "ami" { default = "`curl -s $url`" }
variable "private_domain" { default = "${PRIVATE_DOMAIN}"}
variable "public_domain" { default = "${PUBLIC_DOMAIN}"}
variable "certificate_body_path" { default = "${CERTIFICATE_BODY_PATH}"}
variable "certificate_chain_path" { default = "${CERTIFICATE_CHAIN_PATH}"}
variable "private_key_path" { default = "${PRIVATE_KEY_PATH}"}
variable "dev_app_from_port" { default = "${DEV_APP_FROM_PORT}"}
variable "dev_app_to_port" { default = "${DEV_APP_TO_PORT}"}
variable "qa_app_from_port" { default = "${QA_APP_FROM_PORT}"}
variable "qa_app_to_port" { default = "${QA_APP_TO_PORT}"}
variable "aurora_db_name" { default = "${AURORA_DB_NAME}"}
variable "aurora_db_username" { default = "${AURORA_DB_USERNAME}"}
variable "aurora_db_password" { default = "${AURORA_DB_PASSWORD}"}
variable "aurora_db_instance_count" { default = "${AURORA_DB_INSTANCE_COUNT}"}
variable "aurora_db_instance_class" { default = "${AURORA_DB_INSTANCE_CLASS}"}
variable "aurora_db_publicly_accessible" { default = "${AURORA_DB_PUBLICLY_ACCESSIBLE}"}
EOF